version: "3"
services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app:ro
    command: uvicorn src.main:app --reload --host '0.0.0.0'
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
